version: "3"
services:
  dbt:
    build: .
    volumes:
      - .:/usr/app/
    ports:
      - 8081:8080
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
